
language: kotlin
sudo: false # route the build to the container-based infrastructure for a faster build

# we need to explicitly change to java 8
jdk:
  - oraclejdk8

before_install:
  - "chmod +x gradlew"

script:
  - "./gradlew test jacocoTestReport" # versioneye-update not necessary

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - christoph.pickl@gmail.com


before_cache:
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
